// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime:4.0.30319.42000
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace ConfiaAdmin.My.Resources
{

    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    /// <summary>
    /// Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("ConfiaAdmin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        /// búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _109846
        {
            get
            {
                var obj = ResourceManager.GetObject("109846", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _164531372_453725909175899_8573093330485258261_n
        {
            get
            {
                var obj = ResourceManager.GetObject("164531372_453725909175899_8573093330485258261_n", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _16606
        {
            get
            {
                var obj = ResourceManager.GetObject("16606", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _196766_200
        {
            get
            {
                var obj = ResourceManager.GetObject("196766-200", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _23782214_1949735195350343_1299272425_n
        {
            get
            {
                var obj = ResourceManager.GetObject("23782214_1949735195350343_1299272425_n", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _87578
        {
            get
            {
                var obj = ResourceManager.GetObject("87578", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _875781
        {
            get
            {
                var obj = ResourceManager.GetObject("875781", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _9261
        {
            get
            {
                var obj = ResourceManager.GetObject("9261", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap background_1
        {
            get
            {
                var obj = ResourceManager.GetObject("background-1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap boton_de_quitar_cuadrado
        {
            get
            {
                var obj = ResourceManager.GetObject("boton_de_quitar_cuadrado", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap config
        {
            get
            {
                var obj = ResourceManager.GetObject("config", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap configu
        {
            get
            {
                var obj = ResourceManager.GetObject("configu", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap contraseña
        {
            get
            {
                var obj = ResourceManager.GetObject("contraseña", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap eaad3b05_c22d_49fb_ae4f_2d0e4ff7b0cb
        {
            get
            {
                var obj = ResourceManager.GetObject("eaad3b05-c22d-49fb-ae4f-2d0e4ff7b0cb", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap eliminar
        {
            get
            {
                var obj = ResourceManager.GetObject("eliminar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap empresa_azul
        {
            get
            {
                var obj = ResourceManager.GetObject("empresa_azul", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap grupos_agregar
        {
            get
            {
                var obj = ResourceManager.GetObject("grupos agregar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap home
        {
            get
            {
                var obj = ResourceManager.GetObject("home", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icono_catalogos
        {
            get
            {
                var obj = ResourceManager.GetObject("icono catalogos", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icono_cerrar_empresa
        {
            get
            {
                var obj = ResourceManager.GetObject("icono cerrar empresa", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icono_home
        {
            get
            {
                var obj = ResourceManager.GetObject("icono home", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icono_producto_hogar
        {
            get
            {
                var obj = ResourceManager.GetObject("icono_producto-hogar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icono_reportes
        {
            get
            {
                var obj = ResourceManager.GetObject("icono reportes", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icono_solicitudes
        {
            get
            {
                var obj = ResourceManager.GetObject("icono solicitudes", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap images
        {
            get
            {
                var obj = ResourceManager.GetObject("images", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap impuestos_mas
        {
            get
            {
                var obj = ResourceManager.GetObject("impuestos mas", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap inv
        {
            get
            {
                var obj = ResourceManager.GetObject("inv", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap kisspng_arrow_scalable_vector_graphics_computer_file_compu_download_svg_png_icon_free_download_513522_on_5c55a19ccfefb8_2177330715491158048517
        {
            get
            {
                var obj = ResourceManager.GetObject("kisspng-arrow-scalable-vector-graphics-computer-file-compu-download-svg-png-icon-" + "free-download-513522-on-5c55a19ccfefb8.2177330715491158048517", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap kisspng_computer_icons_symbol_download_5ae1ab4e6c54d2_8156834015247388944437
        {
            get
            {
                var obj = ResourceManager.GetObject("kisspng-computer-icons-symbol-download-5ae1ab4e6c54d2.8156834015247388944437", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap lconfia
        {
            get
            {
                var obj = ResourceManager.GetObject("lconfia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Logo_Confia
        {
            get
            {
                var obj = ResourceManager.GetObject("Logo Confia", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap logo_dando_vueltas
        {
            get
            {
                var obj = ResourceManager.GetObject("logo dando vueltas", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mas
        {
            get
            {
                var obj = ResourceManager.GetObject("mas", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mas1
        {
            get
            {
                var obj = ResourceManager.GetObject("mas1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mas2
        {
            get
            {
                var obj = ResourceManager.GetObject("mas2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap menu_alt_256
        {
            get
            {
                var obj = ResourceManager.GetObject("menu-alt-256", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap minimizar_pestana
        {
            get
            {
                var obj = ResourceManager.GetObject("minimizar_pestana", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap modificar
        {
            get
            {
                var obj = ResourceManager.GetObject("modificar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mostrar
        {
            get
            {
                var obj = ResourceManager.GetObject("mostrar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mostrar1
        {
            get
            {
                var obj = ResourceManager.GetObject("mostrar1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap mostrar2
        {
            get
            {
                var obj = ResourceManager.GetObject("mostrar2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap new_seo2_38_512
        {
            get
            {
                var obj = ResourceManager.GetObject("new_seo2-38-512", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap notificacion
        {
            get
            {
                var obj = ResourceManager.GetObject("notificacion", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ocultar
        {
            get
            {
                var obj = ResourceManager.GetObject("ocultar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ocultar1
        {
            get
            {
                var obj = ResourceManager.GetObject("ocultar1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap ojochico
        {
            get
            {
                var obj = ResourceManager.GetObject("ojochico", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap open_512
        {
            get
            {
                var obj = ResourceManager.GetObject("open-512", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap pantalla_de_bienvenida
        {
            get
            {
                var obj = ResourceManager.GetObject("pantalla de bienvenida", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap png_transparent_calendar_pictogram_payday_loan_text_calendar_logo
        {
            get
            {
                var obj = ResourceManager.GetObject("png-transparent-calendar-pictogram-payday-loan-text-calendar-logo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap png_transparent_calendar_pictogram_payday_loan_text_calendar_logo1
        {
            get
            {
                var obj = ResourceManager.GetObject("png-transparent-calendar-pictogram-payday-loan-text-calendar-logo1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap proveedores
        {
            get
            {
                var obj = ResourceManager.GetObject("proveedores", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap reporte_png_3
        {
            get
            {
                var obj = ResourceManager.GetObject("reporte-png-3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap reproductor
        {
            get
            {
                var obj = ResourceManager.GetObject("reproductor", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SATI
        {
            get
            {
                var obj = ResourceManager.GetObject("SATI", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SATI1
        {
            get
            {
                var obj = ResourceManager.GetObject("SATI1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap usr
        {
            get
            {
                var obj = ResourceManager.GetObject("usr", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap usuario
        {
            get
            {
                var obj = ResourceManager.GetObject("usuario", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap usuario_agregar
        {
            get
            {
                var obj = ResourceManager.GetObject("usuario agregar", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap usuarionegro
        {
            get
            {
                var obj = ResourceManager.GetObject("usuarionegro", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap usuarios
        {
            get
            {
                var obj = ResourceManager.GetObject("usuarios", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}